const additionalPartsList = [
	{ label: "Engine Oil - ₹1200", value: "Engine Oil", cost: 1200 },
	{ label: "Oil Filter - ₹300", value: "Oil Filter", cost: 300 },
	{ label: "Air Filter - ₹350", value: "Air Filter", cost: 350 },
	{ label: "AC Filter - ₹500", value: "AC Filter", cost: 500 },
	{ label: "Fuel Filter - ₹750", value: "Fuel Filter", cost: 750 },
	{ label: "Coolant - ₹600", value: "Coolant", cost: 600 },
	{ label: "Brake Fluid - ₹450", value: "Brake Fluid", cost: 450 },
	{ label: "Transmission Oil - ₹1300", value: "Transmission Oil", cost: 1300 },
	{ label: "Wiper Blades - ₹400", value: "Wiper Blades", cost: 400 },
	{ label: "Battery Check - ₹100", value: "Battery Check", cost: 100 },
	{ label: "Engine Mount - ₹1800", value: "Engine Mount", cost: 1800 },
	{ label: "Clutch Plate - ₹3500", value: "Clutch Plate", cost: 3500 },
	{ label: "Clutch Cable - ₹600", value: "Clutch Cable", cost: 600 },
	{ label: "Gear Oil - ₹850", value: "Gear Oil", cost: 850 },
	{ label: "Spark Plug - ₹400", value: "Spark Plug", cost: 400 },
	{ label: "Ignition Coil - ₹900", value: "Ignition Coil", cost: 900 },
	{ label: "Radiator Flush - ₹700", value: "Radiator Flush", cost: 700 },
	{ label: "Timing Belt - ₹2200", value: "Timing Belt", cost: 2200 },
	{ label: "Timing Chain - ₹3200", value: "Timing Chain", cost: 3200 },
	{ label: "Water Pump - ₹1500", value: "Water Pump", cost: 1500 },
	{
		label: "Power Steering Oil - ₹650",
		value: "Power Steering Oil",
		cost: 650,
	},
	{ label: "Suspension Bush - ₹700", value: "Suspension Bush", cost: 700 },
	{
		label: "Shock Absorber Front - ₹2800",
		value: "Shock Absorber Front",
		cost: 2800,
	},
	{
		label: "Shock Absorber Rear - ₹2600",
		value: "Shock Absorber Rear",
		cost: 2600,
	},
	{ label: "Lower Arm - ₹1400", value: "Lower Arm", cost: 1400 },
	{ label: "Upper Arm - ₹1600", value: "Upper Arm", cost: 1600 },
	{ label: "Tie Rod End - ₹800", value: "Tie Rod End", cost: 800 },
	{
		label: "Steering Rack Boot - ₹900",
		value: "Steering Rack Boot",
		cost: 900,
	},
	{ label: "Brake Pad Front - ₹1800", value: "Brake Pad Front", cost: 1800 },
	{ label: "Brake Pad Rear - ₹1600", value: "Brake Pad Rear", cost: 1600 },
	{ label: "Brake Disc - ₹2500", value: "Brake Disc", cost: 2500 },
	{ label: "Handbrake Cable - ₹700", value: "Handbrake Cable", cost: 700 },
	{ label: "ABS Sensor - ₹1200", value: "ABS Sensor", cost: 1200 },
	{ label: "Wheel Bearing - ₹850", value: "Wheel Bearing", cost: 850 },
	{ label: "Wheel Alignment - ₹600", value: "Wheel Alignment", cost: 600 },
	{ label: "Wheel Balancing - ₹500", value: "Wheel Balancing", cost: 500 },
	{ label: "Tyre Rotation - ₹400", value: "Tyre Rotation", cost: 400 },
	{ label: "Horn - ₹300", value: "Horn", cost: 300 },
	{ label: "Headlight Bulb - ₹450", value: "Headlight Bulb", cost: 450 },
	{ label: "Fog Lamp - ₹900", value: "Fog Lamp", cost: 900 },
	{ label: "Tail Lamp - ₹1000", value: "Tail Lamp", cost: 1000 },
	{ label: "Battery Terminal - ₹200", value: "Battery Terminal", cost: 200 },
	{
		label: "Battery Replacement - ₹4500",
		value: "Battery Replacement",
		cost: 4500,
	},
	{ label: "Starter Motor - ₹3500", value: "Starter Motor", cost: 3500 },
	{ label: "Alternator - ₹4200", value: "Alternator", cost: 4200 },
	{ label: "AC Gas Recharge - ₹1200", value: "AC Gas Recharge", cost: 1200 },
	{ label: "AC Compressor - ₹4800", value: "AC Compressor", cost: 4800 },
	{ label: "Condenser - ₹3000", value: "Condenser", cost: 3000 },
	{ label: "Blower Motor - ₹1500", value: "Blower Motor", cost: 1500 },
	{
		label: "Dashboard Cleaning - ₹700",
		value: "Dashboard Cleaning",
		cost: 700,
	},
	{ label: "Roof Lining - ₹1600", value: "Roof Lining", cost: 1600 },
	{
		label: "Seat Belt Replacement - ₹900",
		value: "Seat Belt Replacement",
		cost: 900,
	},
	{ label: "Window Regulator - ₹1200", value: "Window Regulator", cost: 1200 },
	{ label: "Door Lock - ₹650", value: "Door Lock", cost: 650 },
	{
		label: "Power Window Switch - ₹700",
		value: "Power Window Switch",
		cost: 700,
	},
	{
		label: "Mirror Adjustment Motor - ₹800",
		value: "Mirror Adjustment Motor",
		cost: 800,
	},
	{
		label: "Interior Detailing - ₹1500",
		value: "Interior Detailing",
		cost: 1500,
	},
	{
		label: "Exterior Polishing - ₹1700",
		value: "Exterior Polishing",
		cost: 1700,
	},
	{ label: "Silencer Repair - ₹2000", value: "Silencer Repair", cost: 2000 },
	{
		label: "Underbody Coating - ₹1800",
		value: "Underbody Coating",
		cost: 1800,
	},
	{ label: "Rust Removal - ₹600", value: "Rust Removal", cost: 600 },
	{ label: "Paint Touch-up - ₹900", value: "Paint Touch-up", cost: 900 },
	{ label: "Panel Alignment - ₹700", value: "Panel Alignment", cost: 700 },
	{ label: "Door Alignment - ₹500", value: "Door Alignment", cost: 500 },
	{ label: "Bonnet Lock - ₹400", value: "Bonnet Lock", cost: 400 },
	{ label: "Tailgate Shock - ₹650", value: "Tailgate Shock", cost: 650 },
	{
		label: "Windshield Washer Pump - ₹300",
		value: "Windshield Washer Pump",
		cost: 300,
	},
	{ label: "Washer Fluid - ₹150", value: "Washer Fluid", cost: 150 },
	{
		label: "Number Plate Frame - ₹200",
		value: "Number Plate Frame",
		cost: 200,
	},
	{ label: "Mud Flaps - ₹300", value: "Mud Flaps", cost: 300 },
	{ label: "Tyre Valve - ₹100", value: "Tyre Valve", cost: 100 },
	{
		label: "Tyre Pressure Sensor - ₹800",
		value: "Tyre Pressure Sensor",
		cost: 800,
	},
	{ label: "Reverse Camera - ₹2500", value: "Reverse Camera", cost: 2500 },
	{ label: "Parking Sensor - ₹1200", value: "Parking Sensor", cost: 1200 },
	{
		label: "Central Locking System - ₹2000",
		value: "Central Locking System",
		cost: 2000,
	},
	{
		label: "Remote Key Battery - ₹100",
		value: "Remote Key Battery",
		cost: 100,
	},
	{ label: "Key Programming - ₹600", value: "Key Programming", cost: 600 },
	{ label: "Bluetooth Module - ₹1600", value: "Bluetooth Module", cost: 1600 },
	{ label: "Stereo Speaker - ₹1300", value: "Stereo Speaker", cost: 1300 },
	{ label: "Amplifier - ₹2200", value: "Amplifier", cost: 2200 },
	{ label: "Subwoofer - ₹2800", value: "Subwoofer", cost: 2800 },
	{ label: "Android Stereo - ₹5500", value: "Android Stereo", cost: 5500 },
	{ label: "OBD Scan - ₹300", value: "OBD Scan", cost: 300 },
	{ label: "ECU Reflash - ₹1500", value: "ECU Reflash", cost: 1500 },
	{
		label: "Throttle Body Cleaning - ₹600",
		value: "Throttle Body Cleaning",
		cost: 600,
	},
	{
		label: "Injector Cleaning - ₹1100",
		value: "Injector Cleaning",
		cost: 1100,
	},
	{
		label: "Engine Decarbonization - ₹1800",
		value: "Engine Decarbonization",
		cost: 1800,
	},
	{
		label: "EGR Valve Cleaning - ₹950",
		value: "EGR Valve Cleaning",
		cost: 950,
	},
	{ label: "DPF Cleaning - ₹1200", value: "DPF Cleaning", cost: 1200 },
	{ label: "Turbo Service - ₹3000", value: "Turbo Service", cost: 3000 },
	{ label: "Glow Plug - ₹500", value: "Glow Plug", cost: 500 },
	{
		label: "Intercooler Cleaning - ₹800",
		value: "Intercooler Cleaning",
		cost: 800,
	},
	{ label: "Vacuum Pump - ₹900", value: "Vacuum Pump", cost: 900 },
	{ label: "MAP Sensor - ₹850", value: "MAP Sensor", cost: 850 },
	{ label: "MAF Sensor - ₹950", value: "MAF Sensor", cost: 950 },
	{ label: "Camshaft Sensor - ₹1000", value: "Camshaft Sensor", cost: 1000 },
];
export default additionalPartsList;