const additionalPartsList = [
	{ label: "Engine Oil", value: "Engine Oil", cost: 1200 },
	{ label: "Oil Filter", value: "Oil Filter", cost: 300 },
	{ label: "Air Filter", value: "Air Filter", cost: 350 },
	{ label: "AC Filter", value: "AC Filter", cost: 500 },
	{ label: "Fuel Filter", value: "Fuel Filter", cost: 750 },
	{ label: "Coolant", value: "Coolant", cost: 600 },
	{ label: "Brake Fluid", value: "Brake Fluid", cost: 450 },
	{ label: "Transmission Oil", value: "Transmission Oil", cost: 1300 },
	{ label: "Wiper Blades", value: "Wiper Blades", cost: 400 },
	{ label: "Battery Check", value: "Battery Check", cost: 100 },
	{ label: "Engine Mount", value: "Engine Mount", cost: 1800 },
	{ label: "Clutch Plate", value: "Clutch Plate", cost: 3500 },
	{ label: "Clutch Cable", value: "Clutch Cable", cost: 600 },
	{ label: "Gear Oil", value: "Gear Oil", cost: 850 },
	{ label: "Spark Plug", value: "Spark Plug", cost: 400 },
	{ label: "Ignition Coil", value: "Ignition Coil", cost: 900 },
	{ label: "Radiator Flush", value: "Radiator Flush", cost: 700 },
	{ label: "Timing Belt", value: "Timing Belt", cost: 2200 },
	{ label: "Timing Chain", value: "Timing Chain", cost: 3200 },
	{ label: "Water Pump", value: "Water Pump", cost: 1500 },
	{ label: "Power Steering Oil", value: "Power Steering Oil", cost: 650 },
	{ label: "Suspension Bush", value: "Suspension Bush", cost: 700 },
	{ label: "Shock Absorber Front", value: "Shock Absorber Front", cost: 2800 },
	{ label: "Shock Absorber Rear", value: "Shock Absorber Rear", cost: 2600 },
	{ label: "Lower Arm", value: "Lower Arm", cost: 1400 },
	{ label: "Upper Arm", value: "Upper Arm", cost: 1600 },
	{ label: "Tie Rod End", value: "Tie Rod End", cost: 800 },
	{ label: "Steering Rack Boot", value: "Steering Rack Boot", cost: 900 },
	{ label: "Brake Pad Front", value: "Brake Pad Front", cost: 1800 },
	{ label: "Brake Pad Rear", value: "Brake Pad Rear", cost: 1600 },
	{ label: "Brake Disc", value: "Brake Disc", cost: 2500 },
	{ label: "Handbrake Cable", value: "Handbrake Cable", cost: 700 },
	{ label: "ABS Sensor", value: "ABS Sensor", cost: 1200 },
	{ label: "Wheel Bearing", value: "Wheel Bearing", cost: 850 },
	{ label: "Wheel Alignment", value: "Wheel Alignment", cost: 600 },
	{ label: "Wheel Balancing", value: "Wheel Balancing", cost: 500 },
	{ label: "Tyre Rotation", value: "Tyre Rotation", cost: 400 },
	{ label: "Horn", value: "Horn", cost: 300 },
	{ label: "Headlight Bulb", value: "Headlight Bulb", cost: 450 },
	{ label: "Fog Lamp", value: "Fog Lamp", cost: 900 },
	{ label: "Tail Lamp", value: "Tail Lamp", cost: 1000 },
	{ label: "Battery Terminal", value: "Battery Terminal", cost: 200 },
	{ label: "Battery Replacement", value: "Battery Replacement", cost: 4500 },
	{ label: "Starter Motor", value: "Starter Motor", cost: 3500 },
	{ label: "Alternator", value: "Alternator", cost: 4200 },
	{ label: "AC Gas Recharge", value: "AC Gas Recharge", cost: 1200 },
	{ label: "AC Compressor", value: "AC Compressor", cost: 4800 },
	{ label: "Condenser", value: "Condenser", cost: 3000 },
	{ label: "Blower Motor", value: "Blower Motor", cost: 1500 },
	{ label: "Dashboard Cleaning", value: "Dashboard Cleaning", cost: 700 },
	{ label: "Roof Lining", value: "Roof Lining", cost: 1600 },
	{ label: "Seat Belt Replacement", value: "Seat Belt Replacement", cost: 900 },
	{ label: "Window Regulator", value: "Window Regulator", cost: 1200 },
	{ label: "Door Lock", value: "Door Lock", cost: 650 },
	{ label: "Power Window Switch", value: "Power Window Switch", cost: 700 },
	{
		label: "Mirror Adjustment Motor",
		value: "Mirror Adjustment Motor",
		cost: 800,
	},
	{ label: "Interior Detailing", value: "Interior Detailing", cost: 1500 },
	{ label: "Exterior Polishing", value: "Exterior Polishing", cost: 1700 },
	{ label: "Silencer Repair", value: "Silencer Repair", cost: 2000 },
	{ label: "Underbody Coating", value: "Underbody Coating", cost: 1800 },
	{ label: "Rust Removal", value: "Rust Removal", cost: 600 },
	{ label: "Paint Touch-up", value: "Paint Touch-up", cost: 900 },
	{ label: "Panel Alignment", value: "Panel Alignment", cost: 700 },
	{ label: "Door Alignment", value: "Door Alignment", cost: 500 },
	{ label: "Bonnet Lock", value: "Bonnet Lock", cost: 400 },
	{ label: "Tailgate Shock", value: "Tailgate Shock", cost: 650 },
	{
		label: "Windshield Washer Pump",
		value: "Windshield Washer Pump",
		cost: 300,
	},
	{ label: "Washer Fluid", value: "Washer Fluid", cost: 150 },
	{ label: "Number Plate Frame", value: "Number Plate Frame", cost: 200 },
	{ label: "Mud Flaps", value: "Mud Flaps", cost: 300 },
	{ label: "Tyre Valve", value: "Tyre Valve", cost: 100 },
	{ label: "Tyre Pressure Sensor", value: "Tyre Pressure Sensor", cost: 800 },
	{ label: "Reverse Camera", value: "Reverse Camera", cost: 2500 },
	{ label: "Parking Sensor", value: "Parking Sensor", cost: 1200 },
	{
		label: "Central Locking System",
		value: "Central Locking System",
		cost: 2000,
	},
	{ label: "Remote Key Battery", value: "Remote Key Battery", cost: 100 },
	{ label: "Key Programming", value: "Key Programming", cost: 600 },
	{ label: "Bluetooth Module", value: "Bluetooth Module", cost: 1600 },
	{ label: "Stereo Speaker", value: "Stereo Speaker", cost: 1300 },
	{ label: "Amplifier", value: "Amplifier", cost: 2200 },
	{ label: "Subwoofer", value: "Subwoofer", cost: 2800 },
	{ label: "Android Stereo", value: "Android Stereo", cost: 5500 },
	{ label: "OBD Scan", value: "OBD Scan", cost: 300 },
	{ label: "ECU Reflash", value: "ECU Reflash", cost: 1500 },
	{
		label: "Throttle Body Cleaning",
		value: "Throttle Body Cleaning",
		cost: 600,
	},
	{ label: "Injector Cleaning", value: "Injector Cleaning", cost: 1100 },
	{
		label: "Engine Decarbonization",
		value: "Engine Decarbonization",
		cost: 1800,
	},
	{ label: "EGR Valve Cleaning", value: "EGR Valve Cleaning", cost: 950 },
	{ label: "DPF Cleaning", value: "DPF Cleaning", cost: 1200 },
	{ label: "Turbo Service", value: "Turbo Service", cost: 3000 },
	{ label: "Glow Plug", value: "Glow Plug", cost: 500 },
	{ label: "Intercooler Cleaning", value: "Intercooler Cleaning", cost: 800 },
	{ label: "Vacuum Pump", value: "Vacuum Pump", cost: 900 },
	{ label: "MAP Sensor", value: "MAP Sensor", cost: 850 },
	{ label: "MAF Sensor", value: "MAF Sensor", cost: 950 },
	{ label: "Camshaft Sensor", value: "Camshaft Sensor", cost: 1000 },
];
export default additionalPartsList;
